theme: jekyll-theme-minimal
title: StoryVerse
description: A modern, sleek single-page web application designed for writers, thinkers, and creators to draft, read, and share their stories
show_downloads: false
